---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5d844393ae8e730012a7d831/webhook/forestry
sections:
- type: document
  path: site-metadata.json
  label: Global site config
  templates:
  - config
- type: document
  path: src/pages/index.md
  label: Home
  templates:
  - index
- type: directory
  path: src/pages
  label: Page
  create: all
  match: "**/*"
  exclude: "{index.md,store.md,faq.md,about.md}"
  templates:
  - page
- type: document
  path: src/pages/store.md
  label: Store
  templates:
  - store
- type: document
  path: src/pages/faq.md
  label: FAQ
  templates:
  - faq
- type: document
  path: src/pages/about.md
  label: About
  templates:
  - about
- type: directory
  path: src/pages/category
  label: Categories
  create: all
  match: "**/*"
  templates:
  - categories
- type: document
  path: src/data/promotion.json
  label: Promotion
  templates:
  - promotion
- type: document
  path: src/data/testimonials.json
  label: Testimonials
  templates:
  - testimonials
- type: directory
  path: src/pages/products
  label: Product
  create: all
  match: "**/*"
  templates:
  - products
- type: document
  path: src/data/menus.json
  label: Site Menus
  templates:
  - site_menus
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: npm run forestry:preview
